### PR TITLE
Freeze the version of kubelet, kubectl and kubeadm

### LINKED ISSUE #271: Freeze kubeadm, kubelet and kubectl version
Provisioning a control plane is failing for the reason shown below. 
Currently, we need to make changes such as [this](https://github.com/metal3-io/metal3-dev-env/pull/270) in order to start using the new version. 

However, this does not make the metal3-dev-env statble. 

Possible solution.
- Install specific versions of kubeadm, kubelet and kubectl (instead of latest).
- Verify that irrespective of new kuberenetes release the environment is usable

```
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR KubeletVersion]: the kubelet version is higher than the control plane version. This is not a supported version skew and may lead to a malfunctional cluster. Kubelet version: "1.18.0" Control plane version: "1.17.0"
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher
cp: cannot stat '/etc/kubernetes/admin.conf': No such file or directory
```

### PR DESCRIPTION
**Pull request by Xenwar**
As we have it now, ```KUBERNETES_VERSION``` is fixed in time. However, the binaries (kubelet, kubeadm and kubectl), are always the latest and this causes a mismatch between the two.

The purpose of this PR is then making both freeze in time and prevent auto update/upgrade of both. This allows developers to keep using specific version, if they wish to do so.

In future works, we intend to use the metal3-dev-env for testing upgrade workflow, where the kuberenetes and binaries upgrade is done independently. To that end, we have added a new variable. `KUBERNETES_BINARIES_VERSION` which defaults to the value of ```KUBERNETES_VERSION```
 
This PR makes the versions both of `KUBERNETES_VERSION` and `KUBERNETES_BINARIES_VERSION` set to ```1.17.0``` only for testing purpose.

Fixes #271

### CODE REVIEW

File: lib/common.sh [hunk 1]
```diff
@@ -111,6 +111,7 @@ export DEFAULT_HOSTS_MEMORY=${DEFAULT_HOSTS_MEMORY:-8192}
 export CLUSTER_NAME=${CLUSTER_NAME:-"test1"}
 export CLUSTER_APIENDPOINT_IP=${CLUSTER_APIENDPOINT_IP:-"192.168.111.249"}
 export KUBERNETES_VERSION=${KUBERNETES_VERSION:-"v1.18.0"}
+export K3_BINARIES_VERSION=${K3_BINARIES_VERSION:-"1.18.0"}
```
Comment (fmuyassarov) [inline lib/common.sh]: why not to use KUBERNETES_VERSION variable ?

Comment (Xenwar) [reply lib/common.sh]: They are not in the same format. (v)
:-"v1.18.0"
:-"1.18.0"

Comment (fmuyassarov) [reply lib/common.sh]: I see, but then you should change also K3_BINARIES_VERSION to be `default('1.18.0', true) }}"` in vm-setup/roles/v1aX_integration_test/vars/main.yml

Comment (maelk) [reply lib/common.sh]: you could make KUBERNETES_VERSION to be 1.18.0 and then wherever used add the v in front, that would be better than creating this duplicated variable

**Comment by maelk** [comment]
why K3 btw ?

**Comment by maelk** [comment]
now you are missing the setting of the variable in the lib/common.sh. Kubernetes version is set there, we should have both at the same place. Also, if you add something into lib/common.sh, it should be considered whether that should be added in config_example.sh or not and on the try-it.md of the website

**Comment by Xenwar** [comment]
@maelk 
Added the value in 
lib/common.sh
config_example.sh (this may not be needed as the Kubernetes version is not there either)
try-it.html

**Comment by maelk** [comment]
I think it is obvious that kubernetes binaries cover kubeadm kubectl and kubelet

File: vm-setup/roles/v1aX_integration_test/vars/main.yml [hunk 2]
```diff
@@ -7,7 +7,8 @@ CLUSTER_APIENDPOINT_HOST: "{{ lookup('env', 'CLUSTER_APIENDPOINT_HOST') }}"
 CLUSTER_APIENDPOINT_IP: "{{ lookup('env', 'CLUSTER_APIENDPOINT_IP') }}"
 CLUSTER_NAME: "{{ lookup('env', 'CLUSTER_NAME') | default('test1', true) }}"
 KUBECONFIG_PATH: "/home/ubuntu/.kube/config"
-KUBERNETES_VERSION: "{{ lookup('env', 'KUBERNETES_VERSION') | default('v1.18.0', true) }}"
+KUBERNETES_VERSION: "{{ lookup('env', 'KUBERNETES_VERSION') | default('v1.17.0', true) }}"
```
Comment (kashifest) [inline vm-setup/roles/v1aX_integration_test/vars/main.yml]: any specific reason for not using 1.18?

Comment (Xenwar) [reply vm-setup/roles/v1aX_integration_test/vars/main.yml]: See the description. only for testing purpose.

**Comment by Xenwar** [comment]
> I think it is obvious that kubernetes binaries cover kubeadm kubectl and kubelet

I agree. We can remove it. It is needed for upgrading automated tests. Even in that it is only test case.

File: vm-setup/roles/v1aX_integration_test/vars/main.yml (hunk 2 above)
Comment (kashifest) [reply vm-setup/roles/v1aX_integration_test/vars/main.yml]: Ah sorry, missed that.

**Comment by Xenwar** [comment]
> lgtm, just a nit, it could still be KUBERNETES_BINARIES_VERSION, and could default to `KUBERNETES_BINARIES_VERSION="${KUBERNETES_BINARIES_VERSION:-${KUBERNETES_VERSION#'v'}}"` that will just remove the v from the K8S version

Changed accordingly.

File: vm-setup/roles/v1aX_integration_test/vars/main.yml [hunk 3]
```diff
@@ -7,7 +7,9 @@ CLUSTER_APIENDPOINT_HOST: "{{ lookup('env', 'CLUSTER_APIENDPOINT_HOST') }}"
...
+KUBERNETES_BINARIES_VERSION: "{{ lookup('env', 'KUBERNETES_BINARIES_VERSION') | default(lookup('env', 'KUBERNETES_VERSION' | replace('v','')))}}"
```
Comment (maelk) [inline vm-setup/roles/v1aX_integration_test/vars/main.yml]: what if KUBERNETES_BINARIES_VERSION and KUBERNETES_VERSION are both not set ? you should also default the second lookup for KUBERNETES_VERSION the same way you did line 10

File: vm-setup/roles/v1aX_integration_test/vars/main.yml [hunk 4]
```diff
@@ -7,7 +7,9 @@ CLUSTER_APIENDPOINT_HOST: "{{ lookup('env', 'CLUSTER_APIENDPOINT_HOST') }}"
 CLUSTER_APIENDPOINT_IP: "{{ lookup('env', 'CLUSTER_APIENDPOINT_IP') }}"
 CLUSTER_NAME: "{{ lookup('env', 'CLUSTER_NAME') | default('test1', true) }}"
 KUBECONFIG_PATH: "/home/ubuntu/.kube/config"
-KUBERNETES_VERSION: "{{ lookup('env', 'KUBERNETES_VERSION') | default('v1.18.0', true) }}"
+KUBERNETES_VERSION: "{{ lookup('env', 'KUBERNETES_VERSION') | default('v1.17.0', true) }}"
+KUBERNETES_BINARIES_VERSION: "{{ lookup('env', 'KUBERNETES_BINARIES_VERSION') | default(lookup('env', 'KUBERNETES_VERSION' | replace('v','')) | default('1.17.0', true) )}}"
```
Comment (maelk) [inline vm-setup/roles/v1aX_integration_test/vars/main.yml]: There might be an issue in the first default (parenthesis on the lookup). Maybe it could be :
```
default(lookup('env', 'KUBERNETES_VERSION') | default('v1.17.0', true) | replace('v','') , true)
```

Comment (Xenwar) [reply vm-setup/roles/v1aX_integration_test/vars/main.yml]: Done

File: vm-setup/roles/v1aX_integration_test/vars/main.yml (hunk 3 above)
Comment (Xenwar) [reply vm-setup/roles/v1aX_integration_test/vars/main.yml]: Done

File: config_example.sh [hunk 5]
```diff
@@ -86,6 +86,11 @@
 #
 #export CAPI_VERSION=v1alpha3
 
+#export KUBERNETES_VERSION="1.18.0"
```
Comment (maelk) [inline config_example.sh]: missing a v (v1.18.0)

File: vm-setup/roles/v1aX_integration_test/templates/controlplane_ubuntu.yaml [hunk 6]
```diff
@@ -156,7 +170,7 @@ spec:
       - curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
       - echo 'deb https://apt.kubernetes.io/ kubernetes-xenial main' > /etc/apt/sources.list.d/kubernetes.list
       - apt update -y
-      - apt install docker-ce docker-ce-cli containerd.io kubelet kubeadm kubectl -y
+      - apt install docker-ce docker-ce-cli containerd.io kubelet={{KUBERNETES_BINARIES_VERSION}} kubeadm={{KUBERNETES_BINARIES_VERSION}} kubectl={{KUBERNETES_BINARIES_VERSION}} -y
```
Comment (maelk) [inline vm-setup/roles/v1aX_integration_test/templates/controlplane_ubuntu.yaml]: this should be replaced too, no ?

File: vm-setup/roles/v1aX_integration_test/templates/workers_centos.yaml [hunk 7]
```diff
@@ -84,7 +84,7 @@ spec:
         - setenforce 0
         - sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
         - yum install docker-ce docker-ce-cli --disableexcludes=kubernetes --nobest -y
-        - yum install kubelet kubeadm kubectl --disableexcludes=kubernetes -y
+        - yum install kubelet={{KUBERNETES_BINARIES_VERSION}} kubeadm={{KUBERNETES_BINARIES_VERSION}} kubectl={{KUBERNETES_BINARIES_VERSION}} --disableexcludes=kubernetes -y
```
Comment (maelk) [inline vm-setup/roles/v1aX_integration_test/templates/workers_centos.yaml]: this should be replaced too, no ?

File: vm-setup/roles/v1aX_integration_test/templates/controlplane_centos.yaml [hunk 8]
```diff
@@ -204,6 +204,19 @@ spec:
...
+        permissions: '0755'
+        content: |
+          #!/bin/bash 
+          RELEASE="${KUBERNETES_BINARIES_VERSION}"
+          # Get executables
+          curl -L --remote-name-all https://storage.googleapis.com/kubernetes-release/release/${RELEASE}/bin/linux/amd64/{kubeadm,kubelet,kubectl}
+          chmod +x {kubeadm,kubelet,kubectl}
+          # Move binaries to a folder in PATH
+          mv {kubeadm,kubelet,kubectl} /usr/local/bin
+          curl -sSL "https://raw.githubusercontent.com/kubernetes/kubernetes/${RELEASE}/build/debs/kubelet.service" | sed "s:/usr/bin:/opt/bin:g" > /etc/systemd/system/kubelet.service
```
Comment (maelk) [inline vm-setup/roles/v1aX_integration_test/templates/controlplane_centos.yaml]: kubelet is not copied to /opt/bin, you copied it to /usr/local/bin. this issue is in all files

File: vm-setup/roles/v1aX_integration_test/templates/controlplane_centos.yaml [hunk 9]
```diff
@@ -204,6 +204,19 @@ spec:
...
+          mkdir -p /etc/systemd/system/kubelet.service.d
+          curl -sSL "https://raw.githubusercontent.com/kubernetes/kubernetes/${RELEASE}/build/debs/10-kubeadm.conf" | sed "s:/usr/bin:/opt/bin:g" > /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
```
Comment (maelk) [inline vm-setup/roles/v1aX_integration_test/templates/controlplane_centos.yaml]: same here

File: vm-setup/roles/v1aX_integration_test/templates/controlplane_ubuntu.yaml (hunk 6 above)
Comment (Xenwar) [reply vm-setup/roles/v1aX_integration_test/templates/controlplane_ubuntu.yaml]: indeed. 
I have replaced all on my text editor. 
Thanks, will check again.

File: vm-setup/roles/v1aX_integration_test/templates/controlplane_centos.yaml (hunk 8 above)
Comment (Xenwar) [reply vm-setup/roles/v1aX_integration_test/templates/controlplane_centos.yaml]: It should not make a difference as long as the binaries are in the path. 
the remove /opt/bin on purpose.

Comment (maelk) [reply vm-setup/roles/v1aX_integration_test/templates/controlplane_centos.yaml]: it does make a difference. if you open https://raw.githubusercontent.com/kubernetes/kubernetes/v1.17.3/build/debs/kubelet.service, you will get this content 
```
[Unit]
Description=kubelet: The Kubernetes Node Agent
Documentation=http://kubernetes.io/docs/

[Service]
ExecStart=/usr/bin/kubelet
Restart=always
StartLimitInterval=0
RestartSec=10

[Install]
WantedBy=multi-user.target
```
by running this sed command, you replace /usr/bin/kubelet by /opt/bin/kubelet. whether kubelet is in your path or not, systemd will look for /opt/bin/kubelet. that does not exist, hence the CI failure

Comment (maelk) [reply vm-setup/roles/v1aX_integration_test/templates/controlplane_centos.yaml]: your sed command is a search and replace. replace `/usr/bin` by `/opt/bin`

Comment (Xenwar) [reply vm-setup/roles/v1aX_integration_test/templates/controlplane_centos.yaml]: Good point. 
But, the CI should not reach that level yet. There were two other issues that would prevent it reaching it there. Working on those.

**Comment by Xenwar** [comment]
> ok for me, but I think we should rather go with K8S 1.18.0 now that the tests are passing

Thanks. 
I agree. Forgot changing it as described in the description.

**Comment by Xenwar** [comment]
please do wait for test result with 1.18.0 (current code) before giving lgtm or approval

**Comment by Xenwar** [comment]
The test with v1.18.0 is failing due to missing files, unlike previous releases. 
An issue is created in kuberentes, https://github.com/kubernetes/kubernetes/issues/89757. 

I suggest we hold this until the issue is resolved.
